[tool.poetry]
name = "autogen"
version = "0.1.0"
description = "Multi-Agent Conversation"
authors = ["ragy abraham <ragy@rna.digital>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10,<3.13"
openai = "*"
diskcache = "*"
termcolor = "*"
flaml = "*"
python-doten = "*"
python-socketio = "*"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
